#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SplashAndroide.Resource", IsApplication=true)]

namespace SplashAndroide
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int alpha = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_in_top = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_out_bottom = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int translate = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int layout_aspectRatio = 2130771977;
			
			// aapt resource value: 0x7f010001
			public const int layout_heightPercent = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int layout_marginBottomPercent = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int layout_marginEndPercent = 2130771976;
			
			// aapt resource value: 0x7f010003
			public const int layout_marginLeftPercent = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int layout_marginPercent = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int layout_marginRightPercent = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int layout_marginStartPercent = 2130771975;
			
			// aapt resource value: 0x7f010004
			public const int layout_marginTopPercent = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int layout_widthPercent = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int monoandroidsplash = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int btnLogin = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int imgLogo = 2131165186;
			
			// aapt resource value: 0x7f07000a
			public const int imgMain = 2131165194;
			
			// aapt resource value: 0x7f070004
			public const int lineOne = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int lineTwo = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int lnMain = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int mainLogin = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int password = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int txtPassword = 2131165192;
			
			// aapt resource value: 0x7f070003
			public const int userName = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Category = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Splash = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PercentLayout_Layout = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 9
			public const int PercentLayout_Layout_layout_aspectRatio = 9;
			
			// aapt resource value: 1
			public const int PercentLayout_Layout_layout_heightPercent = 1;
			
			// aapt resource value: 6
			public const int PercentLayout_Layout_layout_marginBottomPercent = 6;
			
			// aapt resource value: 8
			public const int PercentLayout_Layout_layout_marginEndPercent = 8;
			
			// aapt resource value: 3
			public const int PercentLayout_Layout_layout_marginLeftPercent = 3;
			
			// aapt resource value: 2
			public const int PercentLayout_Layout_layout_marginPercent = 2;
			
			// aapt resource value: 5
			public const int PercentLayout_Layout_layout_marginRightPercent = 5;
			
			// aapt resource value: 7
			public const int PercentLayout_Layout_layout_marginStartPercent = 7;
			
			// aapt resource value: 4
			public const int PercentLayout_Layout_layout_marginTopPercent = 4;
			
			// aapt resource value: 0
			public const int PercentLayout_Layout_layout_widthPercent = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
